[package]
name = "rdeebee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1.2", features = ["v4", "serde"] }
rbtree = "0.1.5"
skiplist = "0.4"
bincode = "1.3.3"
serde = { version = "1.0.145", features = ["derive"] }
log = "0.4.17"
thiserror = "1.0.37"
rand = "0.8.5"