[package]
name = "rdeebee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1.2", features = ["v4"] }
rbtree = "0.1.5"
skiplist = "0.4"