apiVersion: v1
kind: Service
metadata:
  name: rdb-server
spec:
  ports:
  - port: 2048
    protocol: TCP
    targetPort: 2048
    # nodePort: 32048
  selector:
    app: rdb-server
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rdb-server
  name: rdb-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rdb-server
  template:
    metadata:
      labels:
        app: rdb-server
    spec:
      containers:
      - image: ratnadeepb/rdb-server:latest
        name: rdb-server
        env:
        - name: TRACE_LEVEL
          value: "info"
        - name: LEASE_TTL
          value: "60"
        - name: REFRESH_INTERVAL
          value: "50"
        - name: ETCD
          value: "128.105.146.151:2379"
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        