apiVersion: v1
kind: Service
metadata:
  name: rdb-server
spec:
  ports:
  - port: 2048
    protocol: TCP
    targetPort: 2048
    # nodePort: 32048
  selector:
    app: rdb-server
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rdb-server
  name: rdb-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rdb-server
  template:
    metadata:
      labels:
        app: rdb-server
    spec:
      containers:
      - image: ratnadeepb/rdb-server:latest
        name: rdb-server
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        