apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-0
  namespace: consul
spec:
  storageClassName: consul-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mydata/storage/"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-1
  namespace: consul
spec:
  storageClassName: consul-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mydata/storage/"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-2
  namespace: consul
spec:
  storageClassName: consul-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mydata/storage/"
