global:
  name: consul
connectInject:
  enabled: false
controller:
  enabled: false

server:
  replicas: 1
  storage: 10Gi
  storageClass: consul-storage
  securityContext:   
    runAsNonRoot: false    
    runAsGroup: 0    
    runAsUser: 0    
    fsGroup: 0